openapi: 3.0.1
info:
  title: PayloadV
  version: 0.1.0
servers:
- url: "{server}:{port}/payloadV"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /path:
    post:
      operationId: postPath
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "202":
          description: Accepted
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /path/{id}:
    get:
      operationId: getPathId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string